### DISCUSSION TITLE
Draggable item shifts to the right by a lot when dragging

### DISCUSSION THREAD

**Discussion by mdodge-ecgrow** [hello-pangea/dnd#758] [Q&A]
I am implementing a Drag and Drop functionality inside a modal in my app.  The modal slides in from the right side and takes up 66vw.  I am guessing that the modal styles, like the transform possibly is what is pushing the draggables over to the right when dragging.
Modal styles:
```css
element {
  position: absolute;

  top: 0px;

  bottom: 0px;

  right: 0px;

  width: 66vw;

  max-height: 100%;

  margin: 0px;

  border: 1px solid rgb(204, 204, 204);

  filter: blur(0px);

  opacity: 1;

  visibility: visible;

  outline: 0px;

  font-size: 1.1em;

  background-color: rgb(255, 255, 255);

  overflow: hidden;

}
.ReactModal__Content--after-open.sliding-modal {
  opacity: 1;

  transform: translateX(0);

  box-shadow: -2rem 2rem 2rem rgba(0, 0, 0, 0.5);

}
.ReactModal__Content.sliding-modal {
  height: 100vh;

  opacity: 0;

  transform: translateX(66vw);

  box-shadow: -2rem 2rem 2rem transparent;

  transition: all 600ms ease-in-out;

}
```

Here is a screenshot of my modal with 2 drag and drop items in the middle.
![image](https://github.com/hello-pangea/dnd/assets/57459547/2f96135e-d2d2-4c4e-bf1c-021d825a7f1b)

And then here is a screenshot of what it looks like when I just start to drag an item, I have not moved it barely at all at this point.
![image](https://github.com/hello-pangea/dnd/assets/57459547/3aa5f6ca-0cb1-43db-8b2e-c550dce42c7a)
