### DISCUSSION TITLE
How do you style the 'Draggable'?

### DISCUSSION THREAD

**Discussion by Kay2dan** [hello-pangea/dnd#791] [Q&A]
A bit of a silly question but I cant seem to find an answer in search. I need to pass a style prop of: 

`width: 100%`

to the Draggable wrapper component. How do you guys do this, considering we cant pass style/ class props to the dnd Draggable component? 

I guess I could use a selector as following however, wanted to clarify whats the approach the community uses?

```css
.parent-of-draggable > :first-child {
   width: 100%
} 
```

Thank you
